name: Check PR
on: [pull_request]

jobs:
  pr:
    name: PR check
    runs-on: [ubuntu-latest]
    env:
      DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
    steps:
      - uses: actions/checkout@v1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Run Lint Check
        shell: bash
        run: ./gradlew lintCheck
      - name: Run unit tests
        shell: bash
        run: ./gradlew --continue build testRelease
      - name: Danger action
        uses: MeilCli/danger-action@v2
        continue-on-error: true
        with:
          plugins_file: 'Gemfile'
          danger_file: 'Dangerfile'
          danger_id: 'danger-pr'
